import { jsPDF } from "jspdf";
import type { Category, ChatSession } from "./placeholder-data";

const BRAND = { primary: "#3D5AFE", text: "#0A1130", muted: "#5A6480", soft: "#F4F6FF" };

function header(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(BRAND.primary);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("VelaGo", 14, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("velago.ai · Voice booking", 14, 20);

  doc.setTextColor(BRAND.text);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, 14, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(BRAND.muted);
  doc.text(subtitle, 14, 51);
}

function detailsBlock(doc: jsPDF, rows: [string, string][], startY: number) {
  let y = startY;
  doc.setDrawColor("#E8EAFF");
  doc.setFillColor(BRAND.soft);
  doc.roundedRect(14, y, 182, rows.length * 10 + 8, 3, 3, "FD");
  y += 8;
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(BRAND.muted);
    doc.text(label.toUpperCase(), 20, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(BRAND.text);
    doc.text(value, 80, y);
    y += 10;
  });
  return y + 4;
}

function footer(doc: jsPDF, refLabel: string, ref: string) {
  doc.setDrawColor("#E8EAFF");
  doc.line(14, 268, 196, 268);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(BRAND.muted);
  doc.text(`${refLabel}: ${ref}`, 14, 276);
  doc.text("Generated by VelaGo · Keep this confirmation for your records.", 14, 282);
}

function airTicket(session: ChatSession): jsPDF {
  const doc = new jsPDF();
  const ref = `IB${Math.floor(1000 + Math.random() * 9000)}-${session.id.toUpperCase()}`;
  header(doc, "Boarding pass", "Iberia · IB3171 · Economy");

  const y = detailsBlock(
    doc,
    [
      ["Passenger", "Alex Johnson"],
      ["From", "London Heathrow (LHR)"],
      ["To", "Madrid Barajas (MAD)"],
      ["Date", "Fri 24 Apr 2026"],
      ["Departure", "09:25"],
      ["Arrival", "13:05"],
      ["Seat", "14C · Aisle"],
      ["Boarding", "08:45 · Gate B12"],
      ["Class", "Economy · Hand bag included"],
    ],
    60,
  );

  // Boarding-pass strip
  doc.setFillColor("#FFFFFF");
  doc.setDrawColor("#E8EAFF");
  doc.roundedRect(14, y, 182, 38, 3, 3, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(BRAND.primary);
  doc.text("LHR", 24, y + 24);
  doc.text("MAD", 150, y + 24);
  doc.setTextColor(BRAND.muted);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("→ 2h 40m · non-stop", 70, y + 16);
  // fake barcode
  for (let i = 0; i < 60; i++) {
    if (Math.random() > 0.45) {
      doc.setFillColor(BRAND.text);
      doc.rect(20 + i * 2.7, y + 30, Math.random() > 0.5 ? 1.2 : 0.6, 5, "F");
    }
  }

  footer(doc, "Booking ref", ref);
  return doc;
}

function parcelLabel(session: ChatSession): jsPDF {
  const doc = new jsPDF();
  const ref = `DHL-${Math.floor(10000000 + Math.random() * 89999999)}`;
  header(doc, "Parcel shipping label", "DHL Express · Next-day delivery");

  let y = detailsBlock(
    doc,
    [
      ["Sender", "Alex Johnson"],
      ["From", "12 Baker Street, London W1U 6TN, UK"],
      ["Receiver", "Marie Schulz"],
      ["To", "Müllerstraße 8, 13353 Berlin, DE"],
      ["Service", "DHL Express · Next-day"],
      ["Weight", "2.4 kg"],
      ["Pickup", "Today, 16:00 – 18:00"],
      ["Insurance", "£100 included"],
    ],
    60,
  );

  // Big tracking number band
  doc.setFillColor(BRAND.text);
  doc.rect(14, y, 182, 22, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(ref, 20, y + 14);
  y += 26;

  // fake barcode
  for (let i = 0; i < 80; i++) {
    if (Math.random() > 0.4) {
      doc.setFillColor(BRAND.text);
      doc.rect(20 + i * 2.1, y, Math.random() > 0.5 ? 1.4 : 0.7, 18, "F");
    }
  }

  footer(doc, "Tracking", ref);
  return doc;
}

function foodOrder(session: ChatSession): jsPDF {
  const doc = new jsPDF();
  const ref = `DEL-${Math.floor(1000 + Math.random() * 9000)}`;
  header(doc, "Order confirmation", "Deliveroo · Thai Square");

  let y = detailsBlock(
    doc,
    [
      ["Customer", "Alex Johnson"],
      ["Deliver to", "12 Baker Street, London"],
      ["Restaurant", "Thai Square · Marylebone"],
      ["Estimated", "Today, 19:30 – 19:50"],
      ["Driver", "Notified once collected"],
    ],
    60,
  );

  // Items table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(BRAND.text);
  doc.text("Items", 14, y);
  y += 4;
  doc.setDrawColor("#E8EAFF");
  doc.line(14, y, 196, y);
  y += 6;

  const items: [string, string, string][] = [
    ["2 ×", "Pad Thai (chicken)", "£18.00"],
    ["1 ×", "Vegetable spring rolls", "£4.50"],
    ["1 ×", "Thai iced tea", "£2.49"],
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  for (const [qty, name, price] of items) {
    doc.text(qty, 14, y);
    doc.text(name, 30, y);
    doc.text(price, 180, y, { align: "right" });
    y += 7;
  }

  y += 2;
  doc.line(14, y, 196, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.text("Total", 14, y);
  doc.text("£24.99", 180, y, { align: "right" });

  footer(doc, "Order ID", ref);
  return doc;
}

export function downloadConfirmation(session: ChatSession) {
  const builders: Record<Category, (s: ChatSession) => jsPDF> = {
    flight: airTicket,
    parcel: parcelLabel,
    food: foodOrder,
    hotel: foodOrder, // fallback
  };
  const doc = builders[session.category](session);
  const safeTitle = session.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`velago-${safeTitle}.pdf`);
}

export function confirmationLabel(category: Category): string {
  if (category === "flight") return "Air ticket (PDF)";
  if (category === "parcel") return "Parcel label (PDF)";
  if (category === "food") return "Order confirmation (PDF)";
  return "Confirmation (PDF)";
}
