import { jsPDF } from "jspdf";
import type { Category } from "./placeholder-data";

const BRAND = { primary: "#3D5AFE", text: "#0A1130", muted: "#5A6480", soft: "#F4F6FF" };

export interface OrderConfirmationData {
  id: string;
  category: Category;
  provider: string;
  service: string;
  date: string;
  price: string;
  status: string;
  reference: string;
  details: { label: string; value: string }[];
}

function drawHeader(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(BRAND.primary);
  doc.rect(0, 0, 210, 30, "F");

  // Simple brand mark + wordmark so PDF carries Velago branding.
  doc.setFillColor("#FFFFFF");
  doc.circle(11, 15, 4, "F");
  doc.setTextColor(BRAND.primary);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("V", 9.6, 16.2);

  doc.setTextColor("#FFFFFF");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("VelaGo", 18, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("velago.ai | Order confirmation", 18, 22);

  doc.setTextColor(BRAND.text);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 14, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(BRAND.muted);
  doc.text(subtitle, 14, 51);
}

function drawRows(doc: jsPDF, rows: { label: string; value: string }[], startY: number): number {
  let y = startY;
  doc.setDrawColor("#E8EAFF");
  doc.setFillColor(BRAND.soft);
  doc.roundedRect(14, y, 182, 198, 3, 3, "FD");
  y += 10;

  for (const row of rows) {
    if (y > 240) break;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(BRAND.muted);
    doc.text(row.label.toUpperCase(), 20, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(BRAND.text);
    const lines = doc.splitTextToSize(row.value || "-", 115) as string[];
    for (const line of lines) {
      if (y > 240) break;
      doc.text(line, 74, y);
      y += 6;
    }
    y += 3;
  }
  return y;
}

function drawFooter(doc: jsPDF, reference: string) {
  doc.setDrawColor("#E8EAFF");
  doc.line(14, 270, 196, 270);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(BRAND.muted);
  doc.text(`Reference: ${reference}`, 14, 278);
  doc.text("Generated by VelaGo. Keep this file for your records.", 14, 284);
}

export function orderConfirmationLabel(category: Category): string {
  if (category === "flight") return "Air ticket (PDF)";
  if (category === "parcel") return "Parcel label (PDF)";
  if (category === "food") return "Order confirmation (PDF)";
  return "Confirmation (PDF)";
}

export function downloadOrderConfirmation(order: OrderConfirmationData) {
  const doc = new jsPDF();
  const title = `${order.provider} confirmation`;
  const subtitle = `${order.service} | ${order.date}`;
  drawHeader(doc, title, subtitle);

  const rows: { label: string; value: string }[] = [
    { label: "Status", value: order.status },
    { label: "Category", value: order.category },
    { label: "Total", value: order.price },
    { label: "Date", value: order.date },
    ...order.details,
  ];

  drawRows(doc, rows, 58);
  drawFooter(doc, order.reference || order.id);

  const safeRef = (order.reference || order.id || "order").replace(/[^a-z0-9-]+/gi, "-").toLowerCase();
  doc.save(`velago-${safeRef}.pdf`);
}
